//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankRacun
    {
        public BankRacun()
        {
            this.MjestoZaposlenja = new HashSet<MjestoZaposlenja>();
        }
    
        public int ID { get; set; }
        public string BrojRacuna { get; set; }
        public string VrstaRacuna { get; set; }
    
        public virtual ICollection<MjestoZaposlenja> MjestoZaposlenja { get; set; }
    }
}
