//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public Kontakt()
        {
            this.Institucija = new HashSet<Institucija>();
        }
    
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public int Uloga { get; set; }
        public string Telefon { get; set; }
        public string email { get; set; }
    
        public virtual Uloga Uloga1 { get; set; }
        public virtual UlogaKontakta UlogaKontakta { get; set; }
        public virtual ICollection<Institucija> Institucija { get; set; }
    }
}
