//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mjesto
    {
        public Mjesto()
        {
            this.Institucija = new HashSet<Institucija>();
            this.Institucija1 = new HashSet<Institucija>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public int Zupanija { get; set; }
    
        public virtual ICollection<Institucija> Institucija { get; set; }
        public virtual ICollection<Institucija> Institucija1 { get; set; }
        public virtual Zupanija Zupanija1 { get; set; }
    }
}
