//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T10_DBEntities : DbContext
    {
        public T10_DBEntities()
            : base("name=T10_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankRacun> BankRacun { get; set; }
        public virtual DbSet<Biljeske> Biljeske { get; set; }
        public virtual DbSet<Dogadaj> Dogadaj { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Faks> Faks { get; set; }
        public virtual DbSet<Institucija> Institucija { get; set; }
        public virtual DbSet<Kontakt> Kontakt { get; set; }
        public virtual DbSet<Mjesto> Mjesto { get; set; }
        public virtual DbSet<MjestoZaposlenja> MjestoZaposlenja { get; set; }
        public virtual DbSet<Odvjetnik> Odvjetnik { get; set; }
        public virtual DbSet<OdvjetnikImaOvlastiNaSpisu> OdvjetnikImaOvlastiNaSpisu { get; set; }
        public virtual DbSet<OdvjetnikStrankaImajuDogadaj> OdvjetnikStrankaImajuDogadaj { get; set; }
        public virtual DbSet<Osoba> Osoba { get; set; }
        public virtual DbSet<Ovlast> Ovlast { get; set; }
        public virtual DbSet<Spis> Spis { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Telefon> Telefon { get; set; }
        public virtual DbSet<TipDogadaja> TipDogadaja { get; set; }
        public virtual DbSet<TipInstitucije> TipInstitucije { get; set; }
        public virtual DbSet<TipOsobe> TipOsobe { get; set; }
        public virtual DbSet<TipPostupka> TipPostupka { get; set; }
        public virtual DbSet<TipSpisa> TipSpisa { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
        public virtual DbSet<UlogaKontakta> UlogaKontakta { get; set; }
        public virtual DbSet<UlogaKorisnika> UlogaKorisnika { get; set; }
        public virtual DbSet<Zupanija> Zupanija { get; set; }
    }
}
