//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odvjetnik
    {
        public Odvjetnik()
        {
            this.OdvjetnikImaOvlastiNaSpisu = new HashSet<OdvjetnikImaOvlastiNaSpisu>();
            this.OdvjetnikStrankaImajuDogadaj = new HashSet<OdvjetnikStrankaImajuDogadaj>();
            this.Spis = new HashSet<Spis>();
            this.Dogadaj = new HashSet<Dogadaj>();
        }
    
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public int Uloga { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Telefon { get; set; }
        public string email { get; set; }
        public Nullable<int> Biljeska { get; set; }
    
        public virtual Biljeske Biljeske { get; set; }
        public virtual UlogaKorisnika UlogaKorisnika { get; set; }
        public virtual ICollection<OdvjetnikImaOvlastiNaSpisu> OdvjetnikImaOvlastiNaSpisu { get; set; }
        public virtual ICollection<OdvjetnikStrankaImajuDogadaj> OdvjetnikStrankaImajuDogadaj { get; set; }
        public virtual ICollection<Spis> Spis { get; set; }
        public virtual ICollection<Dogadaj> Dogadaj { get; set; }
    }
}
