//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public Osoba()
        {
            this.OdvjetnikStrankaImajuDogadaj = new HashSet<OdvjetnikStrankaImajuDogadaj>();
            this.Spis = new HashSet<Spis>();
            this.Email = new HashSet<Email>();
            this.Telefon = new HashSet<Telefon>();
        }
    
        public string OIB { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public string POsoba { get; set; }
        public Nullable<int> TipOsobe { get; set; }
    
        public virtual MjestoZaposlenja MjestoZaposlenja { get; set; }
        public virtual ICollection<OdvjetnikStrankaImajuDogadaj> OdvjetnikStrankaImajuDogadaj { get; set; }
        public virtual TipOsobe TipOsobe1 { get; set; }
        public virtual ICollection<Spis> Spis { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Telefon> Telefon { get; set; }
    }
}
