//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIProjektFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadaj
    {
        public Dogadaj()
        {
            this.OdvjetnikStrankaImajuDogadaj = new HashSet<OdvjetnikStrankaImajuDogadaj>();
            this.Korisnik = new HashSet<Korisnik>();
            this.Spis = new HashSet<Spis>();
        }
    
        public int ID { get; set; }
        public System.DateTime Pocetak { get; set; }
        public System.DateTime Zavrsetak { get; set; }
        public string Opis { get; set; }
        public string Naslov { get; set; }
        public int TipDogadaja { get; set; }
    
        public virtual TipDogadaja TipDogadaja1 { get; set; }
        public virtual ICollection<OdvjetnikStrankaImajuDogadaj> OdvjetnikStrankaImajuDogadaj { get; set; }
        public virtual ICollection<Korisnik> Korisnik { get; set; }
        public virtual ICollection<Spis> Spis { get; set; }
    }
}
