//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIProjektFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucija
    {
        public Institucija()
        {
            this.Kontakt = new HashSet<Kontakt>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string email { get; set; }
        public int TipInstitucije { get; set; }
        public string Faks { get; set; }
    
        public virtual TipInstitucije TipInstitucije1 { get; set; }
        public virtual ICollection<Kontakt> Kontakt { get; set; }
    }
}
