//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIProjektFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public Osoba()
        {
            this.OdvjetnikStrankaImajuDogadaj = new HashSet<OdvjetnikStrankaImajuDogadaj>();
            this.Spis = new HashSet<Spis>();
            this.Spis1 = new HashSet<Spis>();
        }
    
        public string OIB { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public int StatusOsobe { get; set; }
        public int TipOsobe { get; set; }
        public string Racun { get; set; }
        public string Naziv { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Web { get; set; }
    
        public virtual ICollection<OdvjetnikStrankaImajuDogadaj> OdvjetnikStrankaImajuDogadaj { get; set; }
        public virtual StatusOsobe StatusOsobe1 { get; set; }
        public virtual TipOsobe TipOsobe1 { get; set; }
        public virtual ICollection<Spis> Spis { get; set; }
        public virtual ICollection<Spis> Spis1 { get; set; }
    }
}
