//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIProjektFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spis
    {
        public Spis()
        {
            this.Dogadaj = new HashSet<Dogadaj>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public int TipPostupka { get; set; }
        public string Biljeska { get; set; }
        public int NadlezniSud { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public Nullable<System.DateTime> DatumZavrsetak { get; set; }
        public Nullable<System.DateTime> DatumZastare { get; set; }
        public string Stranka { get; set; }
        public string Protustranka { get; set; }
        public int KreiraoOdvjetnik { get; set; }
        public Nullable<int> NadlezniSudac { get; set; }
        public Nullable<bool> Arhiviran { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual Osoba Osoba1 { get; set; }
        public virtual TipPostupka TipPostupka1 { get; set; }
        public virtual ICollection<Dogadaj> Dogadaj { get; set; }
        public virtual Kontakt Kontakt { get; set; }
    }
}
