//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MjestoZaposlenja
    {
        public MjestoZaposlenja()
        {
            this.Osoba = new HashSet<Osoba>();
        }
    
        public string OIB { get; set; }
        public string Naziv { get; set; }
        public string Sjediste { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string WebStranica { get; set; }
        public int RacunBanka { get; set; }
        public int MjestoID { get; set; }
    
        public virtual BankRacun BankRacun { get; set; }
        public virtual ICollection<Osoba> Osoba { get; set; }
    }
}
