//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdvjetnikImaOvlastiNaSpisu
    {
        public int OdvjetnikID { get; set; }
        public int SpisID { get; set; }
        public int OvlastID { get; set; }
    
        public virtual Odvjetnik Odvjetnik { get; set; }
        public virtual Ovlast Ovlast { get; set; }
        public virtual Spis Spis { get; set; }
    }
}
