//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdvjetnikStrankaImajuDogadaj
    {
        public int OdvjetnikID { get; set; }
        public string StrankaOIB { get; set; }
        public int DogadajID { get; set; }
    
        public virtual Dogadaj Dogadaj { get; set; }
        public virtual Odvjetnik Odvjetnik { get; set; }
        public virtual Osoba Osoba { get; set; }
    }
}
