//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ovlast
    {
        public Ovlast()
        {
            this.OdvjetnikImaOvlastiNaSpisu = new HashSet<OdvjetnikImaOvlastiNaSpisu>();
        }
    
        public int ID { get; set; }
        public string Ovlast1 { get; set; }
    
        public virtual ICollection<OdvjetnikImaOvlastiNaSpisu> OdvjetnikImaOvlastiNaSpisu { get; set; }
    }
}
