//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spis
    {
        public Spis()
        {
            this.OdvjetnikImaOvlastiNaSpisu = new HashSet<OdvjetnikImaOvlastiNaSpisu>();
            this.Dogadaj = new HashSet<Dogadaj>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Oznaka { get; set; }
        public int Tip { get; set; }
        public string Biljeska { get; set; }
        public int NadlezniSud { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public Nullable<System.DateTime> DatumZavrsetka { get; set; }
        public string Stranka { get; set; }
        public string Protustranka { get; set; }
        public int TipPostupka { get; set; }
        public Nullable<int> KreiraoOdvjetnik { get; set; }
    
        public virtual Institucija Institucija { get; set; }
        public virtual Odvjetnik Odvjetnik { get; set; }
        public virtual ICollection<OdvjetnikImaOvlastiNaSpisu> OdvjetnikImaOvlastiNaSpisu { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual TipPostupka TipPostupka1 { get; set; }
        public virtual TipSpisa TipSpisa { get; set; }
        public virtual ICollection<Dogadaj> Dogadaj { get; set; }
    }
}
