//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipDogadaja
    {
        public TipDogadaja()
        {
            this.Dogadaj = new HashSet<Dogadaj>();
        }
    
        public int ID { get; set; }
        public string Tip { get; set; }
    
        public virtual ICollection<Dogadaj> Dogadaj { get; set; }
    }
}
